image: kaisky89/debian-git-node-compass

pipelines:
  branches:
    gh-pages:
      - step:
          script:
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/$PATH_TO_WEBSITE/
    BPS-235-compile-js-and-css-on-server:
      - step:
          script:
            - npm install
            - npm run compile
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/
            - curl -T "{$(echo js/*.bundle.js | tr ' ' ',')}" ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/js/ --user $FTP_USERNAME:$FTP_PASSWORD
            - compass compile
            - curl -T "{$(echo stylesheets/* | tr ' ' ',')}" ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/stylesheets/ --user $FTP_USERNAME:$FTP_PASSWORD
