image: samueldebruyn/debian-git

pipelines:
  branches:
    gh-pages:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/$PATH_TO_WEBSITE/
    BPS-235-compile-js-and-css-on-server:
      - step:
          script:
            - apt-get update
            - apt-get -qq install curl
            - curl -sL https://deb.nodesource.com/setup_7.x | bash -
            - apt-get -qq install -y nodejs
            - npm install
            - npm run compile
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/
            - curl -T "{$(echo js/*.bundle.js | tr ' ' ',')}" ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/js/ --user $FTP_USERNAME:$FTP_PASSWORD
            - apt-get -qq install ruby ruby-dev
            - gem update --system
            - gem install compass
            - compass compile
