image: mkenney/npm

pipelines:
  branches:
    gh-pages:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/$PATH_TO_WEBSITE/
    BPS-235-compile-js-and-css-on-server:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - yarn
            - yarn run compile
            - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$SERVER_ADDRESS/cmpg.eu/starters.koeln--test/
